version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: profitpulse-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: profitpulse123
      MONGO_INITDB_DATABASE: firm_data
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - profitpulse-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: profitpulse-mongo-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: profitpulse123
      ME_CONFIG_MONGODB_URL: mongodb://admin:profitpulse123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: profitpulse
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongodb
    networks:
      - profitpulse-network

volumes:
  mongodb_data:
    driver: local

networks:
  profitpulse-network:
    driver: bridge
